##########################################################
# source files
##########################################################
SRCS_CPP += $(foreach dir, $(MOD_PATH)/md5, $(wildcard $(dir)/*.cpp))
SRCS_CC += $(foreach dir, $(MOD_PATH)/md5, $(wildcard $(dir)/*.cc))
SRCS_C += $(foreach dir, $(MOD_PATH)/md5, $(wildcard $(dir)/*.c))
